### ISSUE TITLE
Path collision on windows and case-insentive filesystems

### ISSUE THREAD

**Issue by strikersix23** [Force67/ps4delta#10]
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'code/shared/utl/File.cpp'
  'code/shared/utl/file.cpp'
  'code/shared/utl/File.h'
  'code/shared/utl/file.h'

On windows this would mean they would overwrite eachother

Solution:

Change file names to reflect that they are different

**Comment by Force67** [comment]
Yea i know about these, only the lowercase files are ment to be there. I believe to have fixed this on my current working branch (hlev2) though. Still, thanks for the heads up!
